const movieActionTypes = {
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  ADD_TO_ORDER_START: "ADD_TO_ORDER_START",
  ADD_TO_ORDER_SUCCESS: "ADD_TO_ORDER_SUCCESS",
  ADD_TO_ORDER_FAILURE: "ADD_TO_ORDER_FAILURE",
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
};

export default movieActionTypes;
