const movieActionTypes = {
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  ADD_TO_ORDER_START: "ADD_TO_ORDER_START",
  ADD_TO_ORDER_SUCCESS: "ADD_TO_ORDER_SUCCESS",
  ADD_TO_ORDER_FAILURE: "ADD_TO_ORDER_FAILURE",
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
  ADD_EXPIRY_DATE_START: "ADD_EXPIRY_DATE_START",
  ADD_EXPIRY_DATE_SUCCESS: "ADD_EXPIRY_DATE_SUCCESS",
  ADD_EXPIRY_DATE_FAILURE: "ADD_EXPIRY_DATE_FAILURE",
  FETCH_LONGEVITY_START: "FETCH_LONGEVITY_START",
  FETCH_LONGEVITY_SUCCESS: "FETCH_LONGEVITY_SUCCESS",
  FETCH_LONGEVITY_FAILURE: "FETCH_LONGEVITY_FAILURE",
};

export default movieActionTypes;
