const usersActionTypes = {
  USERS_FETCH_START: "USERS_FETCH_START",
  USERS_FETCH_SUCCESS: "USERS_FETCH_SUCCESS",
  USERS_FETCH_FAILURE: "USERS_FETCH_FAILURE",
  USER_FETCH_START: "USER_FETCH_START",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
  USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
  PASSWORD_RESET_START: "PASSWORD_RESET_START",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAILURE: "PASSWORD_RESET_FAILURE",
};

export default usersActionTypes;
